unique_ids:
  forms:
    Dashboard: UOLQSLLZUBJX5RZX6L7LCHRUNAWR5GCF
    Dashboard.ItemTemplate1: '1718063144493354007209928.39594'
    Dashboard.ItemTemplate2: '1718063524064680757385775.729'
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: QD7J7G74AWQ3LXFKQJ33KKM6JDH5KSCI
    theme.css: K7VXVF2FF56AAEJ3YSHCLO2V4E2LNIDB
  scripts: {}
